project:
  type: book

book:
  title: "The {TEEMS} R package user manual"
  author: "Matthew Cantele"
  site-url: https://teems-org.github.io/
  repo-url: https://github.com/teems-org/teems-org/
  repo-branch: main
  repo-actions: [edit]
  #sharing: [linkedin]
  #page-footer: "How to get help: <https://books.ropensci.org/targets/help.html><br>Copyright 2025, Eli Lilly and Company" 
  chapters:
    - index.qmd
  #   - part: "How to use {targets}"
  #     chapters:
  #       - walkthrough.qmd
  #       - help.qmd
  #       - debugging.qmd
  #   - part: "Concepts and best practices"
  #     chapters:
  #       - functions.qmd
  #       - targets.qmd
  #       - packages.qmd
  #       - projects.qmd
  #       - random.qmd
  #   - part: "Data and files"
  #     chapters:
  #       - data.qmd
  #       - cloud-storage.qmd
  #       - literate-programming.qmd
  #   - part: "Heavy workloads"
  #     chapters:
  #       - crew.qmd
  #       - performance.qmd
  #   - part: "Branching"
  #     chapters:
  #       - dynamic.qmd
  #       - static.qmd
  # appendices:
  #   - hpc.qmd
  #   - drake.qmd
  #   - markdown.qmd

format:
  html:
    theme:
      light: cosmo
      dark: darkly
